model:
  learning_task: LINK_PREDICTION
  encoder:
    layers:
      - - type: EMBEDDING
          output_dim: 100
  decoder:
    type: DISTMULT
    options:
      input_dim: 100
  loss:
    type: SOFTMAX_CE
    options:
      reduction: SUM
  dense_optimizer:
      type: ADAM
      options:
        learning_rate: 0.1
  sparse_optimizer:
      type: ADAGRAD
      options:
        learning_rate: 0.1
storage:
  device_type: cuda
  dataset:
    dataset_dir: ./datasets/livejournal
  edges:
    type: DEVICE_MEMORY
  embeddings:
    type: DEVICE_MEMORY
  save_model: false
training:
  batch_size: 10000
  negative_sampling_method: GAN
  negative_sampling_selected_ratio: 0.2
  negative_sampling:
    num_chunks: 10
    negatives_per_positive: 1000
    degree_fraction: 0.0
    filtered: false
  num_epochs: 25
  epochs_per_shuffle: 1
evaluation:
  batch_size: 1000
  negative_sampling:
    num_chunks: 1
    negatives_per_positive: 10000
    degree_fraction: 0.0
    filtered: false
